Improve benchmark output on pipeline (#340)

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -142,15 +142,9 @@ jobs:
           real_time=$(echo "$output" | grep "^real" | awk 'NR==2 {print $2}')
 
           if echo "$output" | grep -q 'SUCCESS!'; then
-            status="SUCCESS!"
-          else
-            status="FAILURE!"
-          fi
-
-          echo "$real_time $status"
-
-          if [ "$status" == "SUCCESS!" ]; then
+            echo "$real_time"
             exit 0
-          else
-            exit 1
           fi
+
+          echo "FAILURE!"
+          exit 1
